FROM iotaledger/iri:latest

EXPOSE 14265
EXPOSE 14777/udp
EXPOSE 15777

ENV PORT= \
    NEIGHBORS= \
    CONFIG= \
    UPD_RECEIVER_PORT= \
    TCP_RECEIVER_PORT= \
    TESTNET= \
    REMOTE= \
    REMOTE_AUTH= \
    REMOTE_LIMIT_API= \
    SEND_LIMIT= \
    MAX_PEERS= \
    DNS_RESOLUTION_FALSE=

ENTRYPOINT ["./docker-entrypoint.sh"]
